site_name: Drakes - Heroes and Villains
theme: readthedocs 
repo_url: https://github.com/shakna-israel/drakes-heroes-and-villains
site_description: The stakes are raised when everyone comes gunning for Suzie, and her daughter.
site_author: shakna-israel 
use_directory_urls: true 
pages:
 - [index.md, Home]
 - [LICENSE.md, License]
 - [CONTRIBUTING.md, Contributing]
 - [Prologue.md, Prologue]
 - [ChapterOne.md, Chapter One]
 - [ChapterTwo.md, Chapter Two]
 - [ChapterThree.md, Chapter Three]
 - [ChapterFour.md, Chapter Four]
 - [ChapterFive.md, Chapter Five]
 - [ChapterSix.md, Chapter Six]
 - [ChapterSeven.md, Chapter Seven]
 - [ChapterEight.md, Chapter Eight]
 - [ChapterNine.md, Chapter Nine]
 - [ChapterTen.md, Chapter Ten]
 - [Epilogue.md, Epilogue]
